
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jsqlparser.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/commons-fileupload.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jdepend.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jopt-simple.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/commons-cli.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/http-request.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jgrapht.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/scribejava.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/commons-codec.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/joda-time.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/vraptor.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jsoup.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/linq4j-linq4j-0.4/src/mutated/  ~/Study/LittleDarwin/Cases/SecondOrder/linq4j-linq4j-0.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/linq4j.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/jterminal.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/pitest.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/addthis-codec.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/Cases/SecondOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier/commons-lang.txt
