
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jsqlparser.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/commons-fileupload.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jdepend.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jopt-simple.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/commons-cli.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/http-request.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jgrapht.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/scribejava.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/commons-codec.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/joda-time.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/vraptor.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jsoup.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/linq4j-linq4j-0.4/src/mutated/  ~/Study/LittleDarwin/Cases/EightOrder/linq4j-linq4j-0.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/linq4j.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/jterminal.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/pitest.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/addthis-codec.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/Cases/EightOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier8/commons-lang.csv
