
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jsqlparser.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/commons-fileupload.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jdepend.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jopt-simple.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/commons-cli.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/http-request.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jgrapht.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/scribejava.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/commons-codec.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/joda-time.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/vraptor.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jsoup.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/linq4j-linq4j-0.4/src/mutated/  ~/Study/LittleDarwin/Cases/FourthOrder/linq4j-linq4j-0.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/linq4j.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/jterminal.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/pitest.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/addthis-codec.csv
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/Cases/FourthOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier4/commons-lang.csv
