
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/JSqlParser-jsqlparser-0.9.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jsqlparser.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/commons-fileupload-FILEUPLOAD_1_3_1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/commons-fileupload.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/jdepend-2.9.1/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jdepend.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/jopt-simple-4.8/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jopt-simple.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/commons-cli-1.3.1-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/commons-cli.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/http-request-http-request-6.0/lib/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/http-request.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/jgrapht-0.9.1/source/jgrapht-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jgrapht.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/scribejava-1.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/scribejava.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/commons-codec-1.10-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/commons-codec.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/joda-time-2.8.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/joda-time.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/vraptor-vraptor-parent-3.5.5/vraptor-core/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/vraptor.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/jsoup-jsoup-1.8.3/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jsoup.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/linq4j-linq4j-0.4/src/mutated/  ~/Study/LittleDarwin/Cases/ThirdOrder/linq4j-linq4j-0.4/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/linq4j.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/jterminal-jterminal-1.0.1/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/jterminal.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/pitest-pitest-parent-1.1.7/pitest/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/pitest.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/codec-3.3.0/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/addthis-codec.txt
python ~/Study/LittleDarwin/HigherOrderExperiment/MutantIdentifier.py ~/Study/LittleDarwin/Cases/FirstOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/Cases/ThirdOrder/commons-lang3-3.4-src/src/mutated/ ~/Study/LittleDarwin/HigherOrderExperiment/identifier3/commons-lang.txt
